mycardapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('popups.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

popups/urls.py
from django.urls import path
from . import views

app_name = 'popups'
urlpatterns = [
    path('', views.home, name="home"),
    path('add-user/', views.add_user, name="add-user"),
    path('add-card/', views.create_card, name="add"),
    path('details/<str:ref_code>', views.card_details, name="details"),
    path('delete/<str:ref_code>', views.delete_card, name="delete"),
    path('card-preview/<str:ref_code>', views.card_preview, name="preview"),
]

popups/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import SET_NULL
from django.dispatch import receiver
from django.db.models.signals import post_save, pre_save
import uuid
# Create your models here.


def image_file_location(instance, filename):
    return "theme/{0}/{1}".format(instance.id, filename)


class Theme(models.Model):
    name = models.CharField(max_length=100, unique=True)
    image = models.ImageField(upload_to=image_file_location)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name.title()


class PopUp(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    updated_by = models.ForeignKey(
        User, related_name='updated_by', on_delete=models.SET_NULL, null=True)
    ref_code = models.CharField(max_length=15, unique=True)
    business_name = models.CharField(max_length=200)
    content = models.TextField(blank=True, null=True)
    title = models.CharField(max_length=200, null=True, blank=True)
    reinstatement = models.TextField(null=True, blank=True)
    theme = models.ForeignKey(Theme, on_delete=SET_NULL, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.business_name.title()


@receiver(post_save, sender=PopUp)
def post_save_card_create_ref_code(sender, instance, created, *args, **kwargs):
    if created:
        instance.ref_code = str(uuid.uuid4()).replace('-', '')[:15]
        instance.save()

popups/forms.py
from django import forms
from .models import PopUp, Theme
from django.forms import widgets
from django_summernote.widgets import SummernoteWidget


class PopUpForms(forms.ModelForm):
    class Meta:
        model = PopUp
        fields = [
            'business_name',
            'content',
            'title',
            'reinstatement',
            'theme'
        ]
        # widgets = {
        #     'content': SummernoteWidget(attrs={'class': 'form-control', 'summernote': {'width': '100%', 'height': '400px'}})
        # }
        widgets = {
            'content': widgets.TextInput(attrs={'rows': '5'}),
            'reinstatement': widgets.TextInput(attrs={'rows': '5'}),
        }

popups/views.py
from django.http import request
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PopUpForms
from .models import PopUp, Theme
# Create your views here.


@login_required()
def add_user(request):
    form = UserCreationForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            messages.add_message(request, messages.SUCCESS,
                                 'User successfully created name: %s.' % (instance.username.title))
            return redirect('popups:home')
    else:
        form = UserCreationForm(request.POST or None)
    context = {
        'title': 'add user',
        'form': form
    }
    return render(request, 'registration/register_user.html', context)


@login_required()
def home(request):
    popup_cards = PopUp.objects.all()
    card_activity = PopUp.objects.all()[:10]
    form = PopUpForms(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            return redirect('popups:home')
    else:
        form = PopUpForms()
    context = {
        "title": "card list",
        "form": form,
        "cards": popup_cards,
        "card_activity": card_activity
    }
    return render(request, 'home.html', context)


@login_required()
def create_card(request):
    form = PopUpForms(request.POST or None)
    themes = Theme.objects.all()
    if request.method == "POST":
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            return redirect('popups:home')
    else:
        form = PopUpForms()
    context = {
        "title": "add card",
        "form": form,
        "themes": themes
    }
    return render(request, 'create_card.html', context)


@login_required()
def card_details(request, ref_code):
    card = get_object_or_404(PopUp, ref_code=ref_code)
    form = PopUpForms(request.POST or None,
                      request.FILES or None, instance=card)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.updated_by = request.user
        instance.save()
        return redirect('popups:details', ref_code=instance.ref_code)
    context = {
        "title": "card update",
        "instance": card,
        "form": form
    }
    return render(request, "card_details.html", context)


@login_required()
def delete_card(request, *args, **kwargs):
    card_code = kwargs.get('ref_code')
    data = get_object_or_404(PopUp, ref_code=card_code)
    if request.method == "POST":
        data.delete()
        messages.add_message(request, messages.SUCCESS,
                             'Card successfully deleted.')
        return redirect('popups:home')
    context = {
        "title": "delete",
        "instance": data
    }
    return render(request, "delete.html", context)


def card_preview(request, *args, **kwargs):
    card_code = kwargs.get('ref_code')
    data = get_object_or_404(PopUp, ref_code=card_code)
    context = {
        "title": "delete",
        "instance": data
    }
    return render(request, "card_preview.html", context)

popups/templates/card_details.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'popups:home' %}">Cards</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{title|title}}</li>
    </ol>
</nav>
<div class="row">
    <div class="col-xl-8 col-lg-7">
        <div class="card shadow mb-4">
            <div class="card-header">
                {{title|title}}
            </div>
            <form method="POST">
                {% csrf_token %}
                <div class="card-body">
                    {{form|crispy}}
                </div>
                <div class="card-footer">
                    <a href="{{request.META.HTTP_REFERER}}" class="btn btn-outline-secondary btn-sm">Cancel</a>
                    <button type="submit" class="btn btn-primary btn-sm">Update</button>
                </div>
            </form>
        </div>
    </div>
    <div class="col-xl-4 col-lg-5">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Card Preview</h6>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div class="card bg-dark text-white">
                    <img src="{{instance.theme.image.url}}" class="card-img" alt="...">
                    <div class="card-img-overlay">
                        {% if instance.theme.name == "Christmas theme 1" %}
                        <div class="card-preview-1">
                            <p class="card-text">{{ instance.content }}</p>
                            <h5 class="card-title">{{instance.title|title}}</h5>
                            <p class="card-text">{{ instance.reinstatement }}</p>
                        </div>
                        {% endif %}
                        {% if instance.theme.name == "Christmas theme 2" %}
                        <div class="card-preview-2">
                            <p class="card-text">{{ instance.content }}</p>
                            <h5 class="card-title">{{instance.title|title}}</h5>
                            <p class="card-text">{{ instance.reinstatement }}</p>
                        </div>
                        {% endif %}
                        {% if instance.theme.name == "Christmas theme 3" %}
                        <div class="card-preview-3">
                            <p class="card-text">{{ instance.content }}</p>
                            <h5 class="card-title">{{instance.title|title}}</h5>
                            <p class="card-text">{{ instance.reinstatement }}</p>
                        </div>
                        {% endif %}
                    </div>
                </div>
                <br>
                <a href="{% url 'popups:preview' instance.ref_code %}" class="btn btn-outline-info btn-sm">Preview Card</a>
            </div>
            
        </div>
    </div>
</div>

{% endblock %}

popups/templates/card_preview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        @import url("https://fonts.googleapis.com/css2?family=Ephesis&family=Scheherazade New+Slab:wght@400;700&family=Scheherazade+New:wght@400;700&family=Sunshiney&display=swap");
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        .card-container {
            margin-top: 30px;
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
            gap: 20px;
        }


        .card-background-1 {
            background-image: url('{{ instance.theme.image.url }}');
            background-repeat: no-repeat;
            background-size: contain;
            width: 500px;
            height: 500px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        .card-background-1 > h5 {
            font-family: 'Ephesis';
            color: #bf9b3d;
            width: 80%;
            font-size: 3rem;
            text-align: center;
        }
        .card-background-1 > p {
            color: #ffffff;
            font-family: 'Scheherazade New';
            font-size: 1.4rem;
            text-align: center;
            width: 60%;
            line-height: 1;
            padding: 20px;
            font-style: italic;
        }


        .card-background-2 {
            background-image: url('{{ instance.theme.image.url }}');
            background-repeat: no-repeat;
            background-size: contain;
            width: 500px;
            height: 500px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        .card-background-2 > h5 {
            font-family: 'Ephesis';
            color: #bf9b3d;
            width: 80%;
            font-size: 3rem;
            text-align: center;
        }
        .card-background-2 > p {
            color: #bf9b3d;
            font-family: 'Scheherazade New';
            font-size: 1.4rem;
            text-align: center;
            width: 60%;
            line-height: 1;
            padding: 20px;
            font-style: italic;
        }


        .card-background-3 {
            background-image: url('{{ instance.theme.image.url }}');
            background-repeat: no-repeat;
            background-size: contain;
            width: 500px;
            height: 500px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        .card-background-3 > h5 {
            font-family: 'Ephesis';
            color: #bf9b3d;
            width: 80%;
            font-size: 3rem;
            text-align: center;
        }
        .card-background-3 > p {
            color: #ffffff;
            font-family: 'Scheherazade New';
            font-size: 1.4rem;
            text-align: center;
            width: 60%;
            line-height: 1;
            padding: 20px;
            font-style: italic;
        }

        .actions {
            display: flex;
            justify-content: center;
            align-items: center;
            gap: 20px;
        }
        button {
            background-color: #4E73DF;
            padding: 8px;
            border: none;
            color: #fff;
            border-radius: 3px;
        }
        button:hover {
            background-color: #4769cf;
            padding: 8px;
            border: none;
            color: #fff;
            border-radius: 3px;
        }
        a {
            text-decoration: none;
            padding: 8px;
            background-color: #4E73DF;
            color: #fff;
            border-radius: 3px;
        }
    </style>
    <title>{{ instance.business_name|title }}</title>
</head>
<body>
    <div class="card-container">
        {% if instance.theme.name == "Christmas theme 1" %}
        <span hidden id="business-name">{{ instance.business_name }}</span>
        <div class="card-background-1" id="card-image">
            <p>{{instance.content}}</p>
            <h5>{{instance.title|title}}</h5>
            <p>{{instance.reinstatement}}</p>
        </div>
        {% endif %}
        {% if instance.theme.name == "Christmas theme 2" %}
        <span hidden id="business-name">{{ instance.business_name }}</span>
        <div class="card-background-2" id="card-image">
            <p>{{instance.content}}</p>
            <h5>{{instance.title|title}}</h5>
            <p>{{instance.reinstatement}}</p>
        </div>
        {% endif %}
        {% if instance.theme.name == "Christmas theme 3" %}
        <span hidden id="business-name">{{ instance.business_name }}</span>
        <div class="card-background-3" id="card-image">
            <p>{{instance.content}}</p>
            <h5>{{instance.title|title}}</h5>
            <p>{{instance.reinstatement}}</p>
        </div>
        {% endif %}
        <div class="actions">
            <button><a href="{{request.META.HTTP_REFERER}}">Back</a> </button>
            <button id="dl-image">Download Image</button>
        </div>
    </div>

    <script src="https://html2canvas.hertzen.com/dist/html2canvas.min.js"></script>
	<script>
		const businessName = document.getElementById('business-name').textContent;
		// console.log('sample ',businessName)
		document.getElementById('dl-image').onclick = function() {
			const screenshotTarget = document.getElementById('card-image');
			html2canvas(screenshotTarget, {
				scale: 2
			}).then((canvas) => {
				const base64image = canvas.toDataURL('image/jpeg', 1.0);
				console.log(base64image)
				var anchor = document.createElement('a');
				anchor.setAttribute('href', base64image);
				anchor.setAttribute('download', businessName+'.jpg');
				anchor.click();
				anchor.remove();
			});
		}
	</script>
</body>
</html>

popups/templates/delete.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'popups:home' %}">Cards</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{title|title}}</li>
    </ol>
</nav>
<div class="row">
    <div class="col-xl-8 col-lg-7">
        <div class="card shadow mb-4">
            <div class="card-header">
                {{title|title}}
            </div>
            <form action="" method="POST">
                {% csrf_token %}
                <div class="card-body">
                    <p>Are you sure you want to delete <strong>{{ instance.business_name|title }}</strong>?</p>
                </div>
                <div class="card-footer">
                    <a href="{{request.META.HTTP_REFERER}}" class="btn btn-secondary btn-sm">Cancel</a>
                    <input type="submit" value="Delete" class="btn btn-danger btn-sm">
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

popups/templates/home.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'popups:home' %}">Cards</a></li>
    </ol>
</nav>
<div class="row">
    <div class="col-xl-8 col-lg-7">
        <div class="card shadow mb-4">
            <div class="card-header">
                <h6 class="m-0 font-weight-bold text-primary float-left">{{title|title}}</h6>
                <a href="{% url 'popups:add' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm float-right">
                    <i class="fas fa-plus fa-sm text-white-50"></i> 
                    Create Card
                </a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Business Name</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Business Name</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            {% for card in cards %}
                            <tr>
                                <td>
                                    <div class="card mb-3">
                                        <div class="row g-0">
                                          <div class="col-md-4">
                                            <img src="{{card.theme.image.url}}" class="img-fluid rounded-start" alt="{{card.theme.image.url}}">
                                          </div>
                                          <div class="col-md-8">
                                            <div class="card-body">
                                                <h5 class="card-title">
                                                    {{ card.business_name|title }}
                                                </h5>
                                                <p class="card-text">
                                                    {{ card.title|title }}
                                                    <br>
                                                    <small class="text-muted">Created: {{card.created|date}}</small> | <small>by @{{ card.user }}</small>
                                                </p>
                                                <a href="{% url 'popups:preview' card.ref_code %}" class="btn btn-outline-info btn-sm">View</a>
                                                <a href="{% url 'popups:details' card.ref_code %}" class="btn btn-outline-primary btn-sm">Update</a>
                                                <a href="{% url 'popups:delete' card.ref_code %}" class="btn btn-outline-danger btn-sm">Delete</a>
                                            </div>
                                          </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-4 col-lg-5">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Recent Activities</h6>
            </div>
            <!-- Card Body -->
            
            <div class="card-body">
                {% for card in card_activity %}
                <div class="card">
                    <div class="card-body">
                        <p>
                            <a href="{% url 'popups:details' card.ref_code %}">{{card.business_name|title}}</a><br>
                            <small class="text-muted">Created by: @{{card.user|title}}</small>
                            <hr>
                            <!-- <small>Card link: <a href=""></a></small> -->
                            <small class="text-muted">Created: {{card.created|timesince}} ago</small>
                            <br>
                            <small class="text-muted">{% ifchanged card.updated %}Updated: {{card.updated|timesince}} ago by @{{card.updated_by|title}}{% else %}{{ empty }}{% endifchanged %}</small>
                            <br>
                            <a href="{% url 'popups:preview' card.ref_code %}" class="btn btn-outline-info btn-sm float-left">Preview Card</a>
                        </p>
                    </div>
                </div>
                <br>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="createCard" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form method="POST">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Create card</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    {{form|crispy}}
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <input type="submit" class="btn btn-primary" value="Create">
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/includes/footer.html
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Ad On Group 2021</span>
        </div>
    </div>
</footer>

templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Ad On Group {% if title %} | {{ title|title }}{% endif %}</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    <!-- data tables -->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">

</head>

<body id="page-top">
    {% if request.user.is_anonymous %}
    <main role="main" class="flex-shrink-0">
      <div class="container">
          {% block login %}
          {% endblock %}
      </div>
    </main>
    {% else %}
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        {% include 'includes/sidebar.html' %}
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user|title}}</span>
                                <img class="img-profile rounded-circle"
                                    src="{% static 'img/undraw_profile.svg' %}">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                {% if perms.auth.add_user %}
                                <a class="dropdown-item" href="{% url 'popups:add-user' %}">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Add User
                                </a>
                                {% endif %}
                                <a class="dropdown-item" href="{%url 'password_change' %}">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Change Password
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Content Row -->
                    {% block content %}
                    {% endblock %}

                    <!-- Content Row -->
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            {% include 'includes/footer.html' %}
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{%url 'logout'%}">Logout</a>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

    <!-- data tables -->
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>


    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>
    <script src="{% static 'js/demo/datatables-demo.js' %}"></script>

</body>

</html>